name = "Optimized Pack"
author = "Lith"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be94deb3ff2d6f62b4ccb9b852b4edb1af67dd16dc4fd646391027424a373cd7"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
