name = "Optimized Pack"
author = "Lith"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e823c5a0b27884cbe38d245ccaa47025c8e83d53e3f772011a15408b6113ffe9"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
