name = "Optimized Pack"
author = "Lith"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe7bc79f5d98f5f126802148d7bd0d12d04c37faabb04be42dc644619ce8d514"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
