name = "Optimized Pack"
author = "Lith"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5afec1a2528a352544cd23abe0549f344fa6bd8aea02f7473301d162f5537b36"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
