name = "Optimized Pack"
author = "Lith"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b72f6706dad073e82d1e535eb09130f3f8ba5d4e0878638ea14010d63621d1ec"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
