name = "Optimized Pack"
author = "Lith"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e9ef19c6a21ceaeee142548fc8f7b3c5f2c70be9a69aaa0004b8b33ea91655e"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
