name = "Optimized Pack"
author = "Lith"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4cf68b861cb2d3aad1cd87ebaaf294f5bc48cc7a0b03875634fe5524ebc08c02"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
