name = "Optimized Pack"
author = "Lith"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8323ff193d8ca2e9af517c11f59ecca70a5e6237f8d17ab3e6322e3e738c36d4"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
