name = "CIT Resewn"
filename = "CITResewn-0.5.4.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com//data/otVJckYQ/versions/0.5.4/CITResewn-0.5.4.jar"
hash-format = "sha512"
hash = "ffabbad1889404262058be528e45efa5e6aa4044687476758473261c55a0f5ee8efb1612f7dcdad2879fbf446a044307681c1158240a8b8d0fa3cba4ff2e53b9"

[update]
[update.modrinth]
mod-id = "otVJckYQ"
version = "Pqmm2TG5"
